<div class="row mb-5">
    <div class="col-sm-12 col-lg-10 offset-lg-1 text-center">
        <h2 class="text-primary">Tools & Information</h2>
        <p>Below is a handy compiled list of items, npcs, and objects you can look up.</p>
    </div>
</div>

<div class="row">
    <div class="col-md-4 offset-md-4">
        <div class="card border-0 shadow-sm">
            <div class="card-body text-center">
                <h1 class="tool-icon bg-primary rounded-circle mb-4"><i class="fal fa-swords"></i></h1>

                <h4 class="text-primary mb-0">Item List</h4>
                <p class="mb-4">An OSRS Item List</p>

                <p class="mb-0">
                    {{ link_to('tools/items', 'View', 'class' : 'btn btn-primary') }}
                </p>
            </div>
        </div>
    </div>
</div>