<div class="row">
    <div class="col-sm-12">
        <div class="search-box mb-5">
            {{ form('tools/items', 'class' : 'inline-form', 'id' : 'searchform') }}
                {{ text_field("search", 'class' : 'form-control mr-3 rounded-pill py-4 pl-4 input-lg', 'placeholder' : 'Search by item name') }}
                {{ submit_button('Search', 'id' : 'search', 'class' : 'btn btn-primary rounded-pill') }}
            {{ end_form() }}
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div id="results"></div>
    </div>
</div>

<script>
    let page = 1;
    let search = '';
    let locked = true;

    setTimeout(function() {
        loadItems(search, page);
    }, 1000);

    $('#searchform').submit(function(event) {
        event.preventDefault();

        if (locked) {
            return;
        }

        locked = true;
        search = $(this).find("#search").val();
        page   = 1;

        loadItems(search, page);
    });

    $(document).on('click', '#pageBtn', function(event) {
        event.preventDefault();

        if (locked) {
            return;
        }

        locked = true;
        page   = $(this).data('page');
        loadItems(search, page);
    });

    function loadItems(search, page) {
        $.post("{{ url('tools/search') }}", {
            search: search,
            page: page
        }, function(data) {
            $('#results').html(data);
            locked = false;
        });
    }
</script>

{{ content() }}