{{ partial('partials/pagination', ['data' : itemList, 'link' : 'tools/items/']) }}

<div class="card border-0 shadow-sm mb-3">
<table class="table mb-0">
    <thead>
    <tr>
        <th class="text-center" style="width:80px">Id</th>
        <th class="text-center" style="width:34px;"></th>
        <th>Name</th>
    </tr>
    </thead>
    {% for item in itemList.items %}
    <tr>
        <td class="text-center">{{ item['id'] }}</td>
        <td class="text-center">
            <img data-src="{{ url(icon_url~item['id']~'.png') }}" height="32">
        </td>
        <td style="line-height:1em;">{{ item['name'] }}</td>
    </tr>
    {% endfor %}
</table>
</div>

{{ partial('partials/pagination', ['data' : itemList, 'link' : 'tools/items/']) }}

<script>
    $('img').each(function() {
        if ($(this).data("src")) {
            var source = $(this).data("src");
            $(this).attr("src", source);
        }
    });
</script>