<table class="table mb-0">
    <thead>
    <tr>
        <th style="width:80px">Id</th>
        <th style="width:40px"></th>
        <th>Name</th>
        <th class="text-center">Tradeable</th>
        <th class="text-center">Stackable</th>
    </tr>
    </thead>
    {% for item in itemList.items %}
    <tr>
        <td class="text-center">{{ item['id'] }}</td>
        <td>{{ image('img/items/'~item['id']~'.png') }}</td>
        <td style="line-height:1em;">
            {{ item['name'] }}<br>
            <small>{{ item['examine'] }}</small>
        </td>
        <td class="text-center">
            <i class="fal fa-{{ item['tradeable'] ? 'check text-success' : 'times text-danger' }}"></i>
        </td>
        <td class="text-center">
            <i class="fal fa-{{ item['stackable'] ? 'check text-success' : 'times text-danger' }}"></i>
        </td>
    </tr>
    {% endfor %}
</table>