<div class="row">
    <div class="col-sm-12 col-lg-3">
        {{ partial('dashboard/sidebar') }}
    </div>

    <div class="col-sm-12 col-lg-9">
        {{ content() }}

        <div class="card border-0 shadow-sm mb-3" style="height:210px;">
            <div class="card-body p-2">
                <canvas id="voteChart" height="200px"></canvas>
            </div>
        </div>

        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                <div class="row text-center">
                    <div class="col-sm-12 col-lg-3">
                        <i class="fal fa-user fa-lg mt-1 text-white rounded-circle bg-primary stat-icon mb-3"></i>

                        <p class="text-uppercase text-muted mb-0 small">Users</p>
                        <h5 class="font-weight-bold mb-0 text-primary">{{ users|number_format(0) }}</h5>
                    </div>
                    <div class="col-sm-12 col-lg-3">
                        <i class="fal fa-server fa-lg mt-1 text-white rounded-circle bg-danger stat-icon mb-3"></i>

                        <p class="text-uppercase text-muted mb-0 small">Servers</p>
                        <h5 class="font-weight-bold mb-0 text-danger">{{ servers|number_format(0) }}</h5>
                    </div>
                    <div class="col-sm-12 col-lg-3">
                        <i class="fal fa-vote-yea fa-lg mt-1 text-white rounded-circle bg-info stat-icon mb-3"></i>

                        <p class="text-uppercase text-muted mb-0 small">Votes</p>
                        <h5 class="font-weight-bold mb-0 text-info">{{ votes|number_format(0) }}</h5>
                    </div>
                    <div class="col-sm-12 col-lg-3">
                        <i class="fal fa-thumbs-up fa-lg text-white rounded-circle bg-warning stat-icon mb-3"></i>

                        <p class="text-uppercase text-muted mb-0 small">Likes</p>
                        <h5 class="font-weight-bold mb-0 text-warning">{{ likes|number_format(0) }}</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="chartjs"></div>

<script>
    let chartBox = $('#chartjs');

        $.post("{{ url('dashboard/graph') }}", {
            days: 14
        }, function(response) {
            console.log(response);
            chartBox.html(response.toString());
        })
</script>