<div class="row">
    <div class="col-sm-12 col-lg-3">
        {{ partial('dashboard/sidebar') }}
    </div>

    <div class="col-sm-12 col-lg-9">
        {{ content() }}

        <div class="card border-0 shadow-sm mb-3">
            <div class="card-header bg-gradient-primary">
                <h5 class="text-white mb-0">Reports</h5>
            </div>
            <table class="table mb-0">
                {% for reportInfo in reports.items %}

                {% set report = reportInfo.reports %}
                {% set server = reportInfo.servers %}
                {% set user   = reportInfo.users %}

                {% set seo_link = getSeoTitle(server) %}

                <tr>
                    <td>{{ report.username }}</td>
                    <td>
                        {{ link_to('servers/view/'~seo_link, server.title, 'target' : '_blank',
                            'data-toggle' : 'popover', 'title' : 'Test', 'data-content' : 'Test') }}
                    </td>
                    <td class="text-right">{{ date("M. d, Y g:i A", report.date_submitted) }}</td>
                    <td class="text-right">
                        <button type="button" class="btn btn-sm btn-danger"
                                data-toggle="popover"
                                data-trigger="focus"
                                data-content="{{ filter.sanitize(report.reason, 'string') }}"
                                data-placement="left">
                            Info
                        </button>
                        {{ link_to('dashboard/reports?delete='~report.id, 'Delete', 'class' : 'btn btn-danger btn-sm') }}
                    </td>
                </tr>
                {% else %}
                <tr class="text-success">
                    <td class="text-center">
                        <h4><i class="fal fa-smile-wink text-success fa-2x"></i></h4>
                        Yay no reports!
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>

        {{ partial('partials/pagination', ['data' : reports, 'link' : 'dashboard/reports/']) }}
    </div>
</div>

<script>
    $('[data-toggle="popover"]').popover();
    $('.popover-dismiss').popover({
        trigger: 'focus'
    });
</script>