<div class="row">
    <div class="col-sm-12 col-lg-3">
        {{ partial('dashboard/sidebar') }}
    </div>

    <div class="col-sm-12 col-lg-9">
        {{ content() }}

        <div class="card border-0 shadow-sm mb-3">
            <div class="card-header bg-gradient-primary justify-content-between">
                {{ link_to('dashboard/themes?add', 'Add Theme', 'class' : 'btn btn-primary btn-sm float-right') }}

                <h5 class="mb-0 text-white">Themes</h5>
            </div>

            <table class="table table-borderless table-striped mb-0">
                <thead>
                <tr>
                    <th class="py-1 small">Title</th>
                    <th class="py-1 small">Last Edited</th>
                    <th></th>
                </tr>
                </thead>
                {% for theme in themes %}
                <tr>
                    <td>{{ theme['file'] }}</td>
                    <td>{{ theme['modified'] }}</td>
                    <td class="text-right">
                        {{ link_to('dashboard/themes/?edit='~theme['file'], 'Edit', 'class' : 'btn btn-primary btn-sm') }}
                        {{ link_to('dashboard/themes/?delete='~theme['file'], 'Delete', 'class' : 'btn btn-danger btn-sm') }}
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
