{% set loggedIn = user is defined %}

<div class="row mb-5">
    <div class="col-sm-12 col-lg-10 offset-lg-1 text-center">
        <h2>Premium Membership</h2>
        <p>Need a boost? Buying premium will give you instant votes, and votes at the beginning of the month.
            It's basically
            perpetual bonus votes! You'll also be able to use an animated banner, and get a highlighted background to boot!</p>
    </div>
</div>

{{ content() }}
<div id="pp-notice"></div>


<div class="row mb-3">
    {% for package in packages %}
    <div class="col-sm-12 col-lg-3">
        <div class="card border-0 shadow-sm mb-3" data-aos="fade-right" data-aos-delay="{{ loop.index * 200 }}">
            <div class="card-header bg-dark border-0 text-white text-center">
                 {{ package.title }}
            </div>
            <div class="card-header bg-light border-0 text-info text-center bold-font">
                <h2 class="mb-0">
                    ${{ package.price|number_format(2) }}
                </h2>
            </div>
            <div class="list-group list-group-flush text-center">
                {% for feature in package.features|json_decode(true) %}
                {% if feature %}
                <div class="list-group-item border-0">
                    {{ feature }}
                </div>
                {% else %}
                <div class="list-group-item border-0">
                    <i class="fal fa-times text-danger"></i>
                </div>
                {% endif %}
                {% endfor %}
            </div>
            <div class="card-footer">
                <a href="#" class="btn btn-info btn-block {{ loggedIn ? '' : 'disabled' }}" id="buy" data-id="{{ package.id }}">Buy Now</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<div class="row mb-5">
    <div class="col-sm-12">
            <div class="text-center" style="min-height:230px;">
                <div id="paypal-btn"></div>
                <p class="small text-muted mb-0">All payments are a one-time fee and do not recur.</p>
                <p class="small mb-0">By purchasing premium on our platform, you agree to our
                    {{ link_to('terms', 'Terms &amp; Conditions', 'target' : '_blank', 'class' : 'text-info') }}</p>
            </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <h3>Premium Server Example</h3>
        <hr>
        <div class="card shadow-sm mb-3 border-0 text-secondary">
            <table class="table mb-0 tab" style="line-height: 1.2em">
                <tr class="bg-warning">
                    <td class="text-center px-4">
                        <h6 class="mb-0 text-warning"><i class="fas fa-star"></i></h6>
                    </td>
                    <td class="text-truncate" style="max-width:250px;">
                        <p class="text-secondary my-0 small text-uppercase">Server</p>
                        <h6 class="my-0 text-primary text-truncate">
                            <a rel="nofollow" href="#" class="text-info">Your Server Name</a>
                        </h6>
                    </td>
                    <td class="d-md-none d-lg-table-cell text-center">
                        {{ image('img/banner_light.png', 'class' : 'img-fluid server-banner') }}
                    </td>
                    <td class="text-right px-4" style="width:100px;">
                        <h6 class="mb-0">500</h6>
                        <small class="text-muted">Votes</small>
                    </td>
                </tr>
                <tr>
                    <td class="text-center px-4">
                        <h6 class="mb-0 text-muted">2</h6>
                    </td>
                    <td class="text-truncate" style="max-width:250px;">
                        <p class="text-secondary my-0 small text-uppercase">Server</p>
                        <h6 class="my-0 text-primary text-truncate">
                            <a rel="nofollow" href="#" class="text-info">Some other server</a>
                        </h6>
                    </td>
                    <td class="text-right px-4" style="width:100px;" colspan="2">
                        <h6 class="mb-0">0</h6>
                        <small class="text-muted">Votes</small>
                    </td>
                </tr>
                <tr>
                    <td class="text-center px-4">
                        <h6 class="mb-0 text-muted">3</h6>
                    </td>
                    <td class="text-truncate" style="max-width:250px;">
                        <p class="text-secondary my-0 small text-uppercase">Server</p>
                        <h6 class="my-0 text-primary text-truncate">
                            <a rel="nofollow" href="#" class="text-info">Some other server</a>
                        </h6>
                    </td>
                    <td class="text-right px-4" style="width:100px;" colspan="2">
                        <h6 class="mb-0">0</h6>
                        <small class="text-muted">Votes</small>
                    </td>
                </tr>
            </table>
        </div>

    </div>
</div>

{% if loggedIn %}
{{ javascript_include("https://www.paypalobjects.com/api/checkout.js") }}

<script>
    let locked = false;

    $(document).on("click", '#buy', function(event) {
        event.preventDefault();

        if (locked) {
            return;
        }

        locked = true;
        var id = $(this).data("id");

        $('#paypal-btn').removeClass("text-danger").html("<i class='fal fa-spinner fa-pulse fa-3x mb-3'></i>");

        $.post("{{ url('premium/button') }}", {
            pid: id
        }, function(data) {
            try {
                let json = JSON.parse(data);

                if (!json.success) {
                    $('#paypal-btn').addClass("text-danger").html(json.message);
                }
            } catch (err) {
                $('#paypal-btn').removeClass("text-danger").html(data);
            }

            locked = false;
        })

    })

</script>
{% endif %}

<script>AOS.init();</script>