{{ javascript_include('https://cdn.quilljs.com/1.3.6/quill.min.js') }}

<script>
    var apiUrl = 'https://api.imgur.com/3/image';
    var apiKey = '{{ constant("IMGUR_KEY") }}';

    var toolbarOptions = [
        [{ 'header': [1, 2, 3, 4, 5, 6, false] }, {'size' : []}],
        ['bold', 'italic', 'underline', { 'color': [] }, 'link'],
        ['blockquote', 'code-block'],
        [{ 'list': 'ordered'}, { 'list': 'bullet' }],
        [{ 'align': [] }],
        ['clean']
    ];

    var quill = new Quill('#editor', {
        theme: 'snow',
        modules: {
            toolbar: toolbarOptions
        }
    });

    $("#postform").on("submit", function (event) {
        event.preventDefault();
        var body  = $(this).find(".ql-editor").html();

        $(this).find("#editor-form").html(body);

        $(this)[0].submit();
    });

</script>