<div class="card shadow-sm bg-gradient border-0 mb-3">
    <div class="card-body text-white text-center">
        <i class="fab fa-discord fa-4x mr-2 mb-3"></i>
        <h3 class="text-white mb-0 mt-1" style="line-height:1em;">
            {{ server['name'] }}
        </h3>
        <p>{{ members|count|number_format(0) }} members</p>

        <a class="btn btn-link text-white" href="https://discord.gg/{{ invite['code'] }}" target="_blank">
            Join Server
        </a>
    </div>
</div>

{{ content() }}