<section class="section section-lg py-5 bg-gradient-primary">
    <div class="container">
            <div class="col-md-10 offset-md-1 order-md-1 text-center">
                <div class="pr-md-5">
                    <h3 class="text-white">Want the latest News and Awesome Stuff?</h3>
                    <p class="mb-5 text-white-50">Join our discord to keep up-to-date with everything going on around the Nexus, and if you're looking
                    for a server to join, you can find those there, and Server owners get a fancy rank too!</p>

                    <a href="https://discord.gg/D5bQ4qG" target="_blank" class="btn btn-white">
                        Join Discord
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-lg-9">
                {{ content() }}

                {% for article in articles %}
                {% set avatar = avatar(article.user_id, article.avatar) %}
                <div class="card border-0 shadow-sm mb-3 overflow-hidden">
                    <div class="card-body p-0">
                        <div class="d-flex flex-lg-row flex-column">
                            <div class="flex-fill text-center py-lg-5 py-sm-3 card-author">
                                {{ image(avatar, 'class' : 'rounded-circle mb-3', 'width' : '96px') }}

                                <h5 class="mb-0">{{ article.username }}</h5>
                                <p class="text-muted mb-0">{{ article.role }}</p>
                            </div>
                            <div class="flex-fill w-100 py-5 px-4 card-message">
                                {{ article.news_body }}
                                <p class="small text-muted mb-0">
                                    {{ date("M. d, Y | g:i A", article.date_posted) }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

            <div class="col-sm-12 col-lg-3">
                {% if user is not defined %}
                <button type="button" class="btn btn-primary btn-block btn-lg mb-3" data-toggle="modal" data-target="#loginModal">
                    Login
                </button>
                {% endif %}

                <div class="card border-0 shadow-sm mb-3">
                    <div class="card-body text-right">
                        <i class="fal fa-user fa-lg text-white rounded-circle bg-primary stat-icon float-left"></i>
                        <h5 class="font-weight-bold mb-0 text-primary">{{ users|number_format(0) }}</h5>
                        <p class="text-uppercase text-muted mb-0 small">Users</p>
                    </div>
                </div>

                <div class="card border-0 shadow-sm mb-3">
                    <div class="card-body text-right">
                        <i class="fal fa-server fa-lg text-white rounded-circle bg-danger stat-icon float-left"></i>

                        <h5 class="font-weight-bold mb-0 text-danger">{{ servers|number_format(0) }}</h5>
                        <p class="text-uppercase text-muted mb-0 small">Servers</p>
                    </div>
                </div>

                <div class="card border-0 shadow-sm mb-3">
                    <div class="card-body text-right">
                        <i class="fal fa-vote-yea fa-lg text-white rounded-circle bg-info stat-icon float-left"></i>

                        <h5 class="font-weight-bold mb-0 text-info">{{ votes|number_format(0) }}</h5>
                        <p class="text-uppercase text-muted mb-0 small">Votes</p>
                    </div>
                </div>

                <div class="card border-0 shadow-sm mb-3">
                    <div class="card-body text-right">
                        <i class="fal fa-thumbs-up fa-lg text-white rounded-circle bg-warning stat-icon float-left"></i>

                        <p class="text-uppercase text-muted mb-0 small">Likes</p>
                        <h5 class="font-weight-bold mb-0 text-warning">{{ likes|number_format(0) }}</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <hr>
        <div class="row row-grid justify-content-center">
            <div class="col-lg-8 text-center">
                <h2 class="display-3">Do you like this project? <span class="text-success">Fork us on Github!</span></h2>
                <p class="lead">
                    Feel free to fork us on github and submit any issues you come across!
                </p>
                <div class="btn-wrapper">
                    <a href="https://github.com/OGKingFox/Toplist" class="btn btn-primary mb-3 mb-sm-0">
                        Fork on Github
                    </a>
                </div>

            </div>
        </div>
    </div>
</section>

<script>
    /*setTimeout(function() {
        $.post('{{ url("index/discord") }}', function(data) {
            $('#discord').html(data);
        });
    }, 1000);8*/
</script>