{{ content() }}

<div class="row">
    <div class="col-sm-12">
        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                <div class="float-right">
                    {% if myServer is not null %}
                    {{ link_to('profile/edit', '<i class="fal fa-plus-circle fa-fw"></i> Manage Server', 'class' : 'btn btn-info') }}
                    {% else %}
                    {% if user is defined %}
                    {{ link_to('profile/add', '<i class="fal fa-plus-circle fa-fw"></i> Add Server', 'class' : 'btn btn-info') }}
                    {% endif %}
                    {% endif %}

                    <div class="btn-group" role="group">
                        <button id="btnGroupDrop1" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fal fa-list-alt fa-fw"></i> {{ game.title }}
                        </button>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="btnGroupDrop1">
                            {% for g in games %}
                            {% set seo_title = g.id~'-'~str_replace(" ", "-", g.title|lowercase) %}
                            {{ link_to('game/'~seo_title, g.title, 'class' : 'dropdown-item') }}
                            {% endfor %}
                        </div>
                    </div>
                </div>

                {{ form('', 'class' : 'form-inline search-form', 'method' : 'post') }}
                {{ text_field('', 'class' : 'form-control rounded-pill', 'placeholder' : 'Search...') }}
                <button type="submit" class="btn btn-info rounded-pill">Search</button>
                {{ end_form() }}
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="card shadow-sm mb-3 border-0 text-secondary">
            <table class="table mb-0 tab" style="line-height: 1.2em">
                {% for server in servers.items %}
                <?php $seo_title = Servers::genSeoTitle($server); ?>
                <tr>
                    <td class="text-center px-4">
                        <h4 class="mb-0 text-muted">1</h4>
                    </td>
                    <td>
                        <p class="text-secondary my-0 small">SERVER</p>
                        <h5 class="my-0 text-primary">
                            {{ link_to('view/'~seo_title, server.title, 'class' : 'text-info') }}
                        </h5>
                    </td>
                    <td class="d-md-none d-lg-table-cell">
                        {{ image(server.banner_url, 'class' : 'img-fluid server-banner') }}
                    </td>
                    <td class="text-center px-4" style="width:150px;">
                        <h5 class="mb-0 badge badge-info py-2 badge-pill w-100">
                            {{ server.votes }}
                        </h5><br>
                        <small class="text-muted">Vote{{ server.votes > 1 ? 's' : '' }}</small>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

<div class="mb-3">
    {% set game_seo = game.id~'-'~str_replace(" ", "-", game.title|lowercase) %}

    {% if servers.total_pages > 0 %}
    <div class="row my-4">
        <div class="btn-group" role="group" aria-label="Basic example" style="margin:auto;">
            {% set link = username is defined ? '/'~username : '' %}
            {{ link_to('game/'~game_seo~'/'~servers.first, '<i class="fal fa-angle-double-left"></i>', 'class' : 'btn btn-info') }}
            {{ link_to('game/'~game_seo~'/'~servers.before, '<i class="fal fa-angle-left"></i>', 'class' : 'btn btn-info') }}

            {{ link_to('', 'Page '~servers.current~' of '~servers.total_pages, 'class' : 'btn btn-info disabled') }}

            {{ link_to('game/'~game_seo~'/'~servers.next, '<i class="fal fa-angle-right"></i>', 'class' : 'btn btn-info') }}
            {{ link_to('game/'~game_seo~'/'~servers.last, '<i class="fal fa-angle-double-right"></i>', 'class' : 'btn btn-info') }}
        </div>
    </div>
    {% endif %}
</div>