<div class="row">
    <div class="col-sm-12 col-xl-8">
        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body pb-0">
                <canvas id="donateChart" height="200px"></canvas>
            </div>
            <div class="card-body pb-2 pt-0 text-center small text-muted">
                Votes reset at the end of the month in <strong>{{ resetIn }}</strong>
            </div>
        </div>

        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                <div class="float-right">
                    {{ link_to(server.website, '<i class="fal fa-globe fa-fw"></i>', false, 'target' : '_blank',
                        'class' : 'btn btn-primary btn-sm border-0',
                        'data-toggle' : 'tooltip', 'title' : 'Visit Website') }}

                    {{ link_to(server.website, '<i class="fal fa-thumbs-up fa-fw"></i> +1', false, 'target' : '_blank',
                        'class' : 'btn btn-primary btn-sm border-0',
                        'data-toggle' : 'tooltip', 'title' : 'Like this Server') }}
                </div>
                <h5>{{ server.title }}</h5>
                <hr>
                {{ server.info }}
            </div>
        </div>

        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                <h5>Comments</h5>
                <hr>

                <hr>
                {{ form('view/'~seo_title, 'method' : 'post') }}
                <div class="form-group">
                    <p class="small text-muted">Leave a comment below!</p>
                    <div id="editor" class="mb-3"></div>
                    <textarea name='info' id='editor-form' style='display:none'></textarea>
                </div>
                <div class="form-group">
                    {{ submit_button('Create Reply', 'class' : 'btn btn-dark') }}
                </div>
                {{ end_form() }}

            </div>
        </div>
        {{ content() }}
    </div>

    <div class="col-sm-12 col-xl-4">
        <div class="card border-0 shadow-sm mb-3">
            <div class="list-group list-group-flush">
                <div class="list-group-item">
                    Added By <span class="float-right text-right">{{ server.owner_tag }}<br><small>ID: {{ server.owner_id }}</small></span>
                </div>
                <div class="list-group-item">
                    Rank <span class="float-right">1</span>
                </div>
                <div class="list-group-item">
                    Total Votes <span class="float-right">{{ votes }}</span>
                </div>
                <div class="list-group-item">
                    Likes <span class="float-right">{{ likes }}</span>
                </div>
                <div class="list-group-item">
                    Date Created <span class="float-right">{{ date('M. j, Y', server.date_created) }}</span>
                </div>
            </div>
        </div>

        <p class="small text-muted text-center">
            All server data is cached for up to 15 seconds, so updates may not appear instantly.
        </p>
    </div>
</div>

{{ partial('partials/quilljs-basic') }}
{{ javascript_include("js/chart.min.js") }}

<script>
    var ctx2 = document.getElementById("donateChart").getContext('2d');

    window.chartColors = {
        red:    'rgb(255, 99, 132)',
        orange: 'rgb(255, 159, 64)',
        yellow: 'rgb(255, 205, 86)',
        green:  'rgb(75, 192, 192)',
        blue:   'rgb(54, 162, 235)',
        purple: 'rgb(153, 102, 255)',
        grey:   'rgb(201, 203, 207)'
    };

    var options = {};

    options.maintainAspectRatio = false;
    options.response = true;
    options.elements = {};
    options.elements.line = {};
    options.elements.point = {};
    options.scales = {};
    options.title = {};
    options.tooltips = {};
    options.tooltips.callbacks = {};
    options.legend = {};
    options.legend.labels = {};
    options.elements.line.borderWidth = 1;
    options.elements.line.fill = true;
    options.elements.line.tension = 0.3;
    options.elements.point.radius = 2;
    options.title.display = true;
    options.title.text = 'Votes for {{ date("F") }}';
    options.legend.display = false;
    options.legend.position = "top";
    options.animation = false;

    new Chart(ctx2, {
        type: 'line',
        data: {
            title: 'test',
            labels: [<?= implode(',', $days) ?>],
            datasets: [
                {
                    label: 'Votes',
                    data: <?= json_encode(array_values($voteData)) ?>,
                    borderColor: 'rgba(54, 162, 235, 1)',
                    backgroundColor: 'rgba(54, 162, 235, 0.03)'
                }
            ]
        },
        options: options
    });
</script>