<div class="row">
    <div class="col-sm-12 col-xl-8">
        {{ content() }}
        <div id="alerts"></div>

        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body pb-0">
                <canvas id="donateChart" height="200px"></canvas>
            </div>
            <div class="card-body pb-2 pt-0 text-center small text-muted">
                Votes reset at the end of the month in <strong>{{ resetIn }}</strong>
            </div>
        </div>

        <div class="card border-0 shadow-sm mb-3">
            <div class="card-header bg-white">
                <div class="float-right">
                    {{ link_to(server.website, '<i class="fal fa-globe fa-fw"></i>', false, 'target' : '_blank',
                        'class' : 'btn btn-primary btn-sm border-0',
                        'data-toggle' : 'tooltip', 'title' : 'Visit Website') }}

                    {{ link_to(server.website, '<i class="fal fa-thumbs-up fa-fw"></i> Like', false, 'target' : '_blank',
                        'class' : 'btn btn-primary btn-sm border-0',
                        'id' : 'like', 'data-id' : server.id,
                        'data-toggle' : 'tooltip', 'title' : 'Like this Server') }}
                </div>
                <h4 class="mb-0">{{ server.title }}</h4>
            </div>
            <div class="card-body">
                {{ server.info }}
            </div>
        </div>

        <div class="card border-0 shadow-sm mb-3">
            <div class="card-header bg-white">Comments</div>
            <div class="card-body">
                <div class="comment-form"></div>
                {{ form('view/'~seo_title, 'method' : 'post', 'class' : 'form-inline', 'id' : 'comment-form') }}
                <div class="form-group">
                    {{ text_field('comment', 'class' : 'form-control mr-2', 'placeholder' : 'Type a comment!',
                        'style' : 'min-width: 350px;') }}
                </div>
                {{ hidden_field(security.getTokenKey(), 'value' : security.getToken()) }}
                <div class="form-group">
                    <button class="btn btn-dark" type="submit"><i class="fal fa-paper-plane"></i></button>
                </div>
                {{ end_form() }}
            </div>

            <div class="list-group list-group-flush">
                {% for comment in comments.items %}
                <?php $avatar = Functions::getAvatarUrl($comment->user_id, $comment->avatar); ?>
                <div class="list-group-item {{ comment.user_id is server.user.user_id ? 'bg-warning' : '' }}">
                    <div class="d-flex">
                        <div class="flex-fill">
                            {{ image(avatar, 'width' : '42px;', 'class' : 'rounded-circle mr-3') }}
                        </div>
                        <div class="flex-fill w-100">
                            <p class="small my-0">{{ filter.sanitize(comment.username, 'string') }} | {{ date('m/d/Y h:i A', comment.date_posted) }}</p>
                            <p class="my-0">{{ filter.sanitize(comment.comment, 'string') }}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="mb-3">
            {% if comments.total_pages > 0 %}
            <div class="row my-4">
                <div class="btn-group" role="group" aria-label="Basic example" style="margin:auto;">
                    {% set link = username is defined ? '/'~username : '' %}
                    {{ link_to('view/'~seo_title~'?page='~comments.first, '<i class="fal fa-angle-double-left"></i>', 'class' : 'btn btn-light') }}
                    {{ link_to('view/'~seo_title~'?page='~comments.before, '<i class="fal fa-angle-left"></i>', 'class' : 'btn btn-light') }}

                    {{ link_to('', 'Page '~comments.current~' of '~comments.total_pages, 'class' : 'btn btn-light disabled') }}

                    {{ link_to('view/'~seo_title~'?page='~comments.next, '<i class="fal fa-angle-right"></i>', 'class' : 'btn btn-light') }}
                    {{ link_to('view/'~seo_title~'?page='~comments.last, '<i class="fal fa-angle-double-right"></i>', 'class' : 'btn btn-light') }}
                </div>
            </div>
            {% endif %}
        </div>
    </div>

    <div class="col-sm-12 col-xl-4">
        <div class="card border-0 shadow-sm mb-3">
            <div class="list-group list-group-flush">
                <div class="list-group-item">
                    Added By <span class="float-right text-right">{{ server.owner_tag }}<br><small>ID: {{ server.owner_id }}</small></span>
                </div>
                <div class="list-group-item">
                    Total Votes <span class="float-right">{{ votes }}</span>
                </div>
                <div class="list-group-item">
                    Likes <span class="float-right" id="likes">{{ likes }}</span>
                </div>
                <div class="list-group-item">
                    Date Created <span class="float-right">{{ date('M. j, Y', server.date_created) }}</span>
                </div>
            </div>
        </div>

        {% if server.discord_id is not -1 %}
        <iframe src="https://discordapp.com/widget?id={{server.discord_id }}&theme=light" width="350"
                height="500" allowtransparency="true" frameborder="0" class="shadow-sm"></iframe>
        {% endif %}

        <p class="small text-muted text-center">
            All server data is cached for up to 15 seconds, so updates may not appear instantly.
        </p>

    </div>
</div>

{{ javascript_include("js/chart.min.js") }}

<script>
    var locked = false;

    $(document).on('click', '#like', function(event) {
        event.preventDefault();

        if (locked) {
            return;
        }

        locked = true;

        var id = $(this).data("id");

        $.post('{{ url("like") }}', {
            id: id
        }, function(data) {
            locked = false;
            try {
                var json = JSON.parse(data);
                var success = json.success;
                var msg = json.message;

                if (success) {
                    var count = json.count.amount;
                    $('#likes').html(count);
                }

                displayMsg(msg, success);
            } catch (err) {

            }

            console.log(data);
        });

    });

    function displayMsg(message, success) {
        var type = success ? 'success' : 'danger';

        $('#alerts').html("<div class='alert alert-"+type+" alert-dismissible fade show'>" +
            "<button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">\n" +
            "<span aria-hidden=\"true\">&times;</span>\n" +
            "</button>"+message+"</div>");
    }

    var ctx2 = document.getElementById("donateChart").getContext('2d');

    window.chartColors = {
        red:    'rgb(255, 99, 132)',
        orange: 'rgb(255, 159, 64)',
        yellow: 'rgb(255, 205, 86)',
        green:  'rgb(75, 192, 192)',
        blue:   'rgb(54, 162, 235)',
        purple: 'rgb(153, 102, 255)',
        grey:   'rgb(201, 203, 207)'
    };

    var options = {};

    options.maintainAspectRatio = false;
    options.response = true;
    options.elements = {};
    options.elements.line = {};
    options.elements.point = {};
    options.scales = {};
    options.title = {};
    options.tooltips = {};
    options.tooltips.callbacks = {};
    options.legend = {};
    options.legend.labels = {};
    options.elements.line.borderWidth = 1;
    options.elements.line.fill = true;
    options.elements.line.tension = 0.3;
    options.elements.point.radius = 2;
    options.title.display = true;
    options.title.text = 'Votes for {{ date("F") }}';
    options.legend.display = false;
    options.legend.position = "top";
    options.animation = false;

    new Chart(ctx2, {
        type: 'line',
        data: {
            title: 'test',
            labels: [<?= implode(',', $days) ?>],
            datasets: [
                {
                    label: 'Votes',
                    data: <?= json_encode(array_values($voteData)) ?>,
                    borderColor: 'rgba(54, 162, 235, 1)',
                    backgroundColor: 'rgba(54, 162, 235, 0.03)'
                }
            ]
        },
        options: options
    });
</script>