<div class="row">
    <div class="col-sm-12 col-lg-12">
        {{ content() }}

        <div class="card border-0 shadow-sm mb-0 mb-3 bg-info text-white">
            <div class="card-body">
                <p class="mb-0">After you've created your server, you can go to your profile to edit server ip, port, manage
                    images and more.</p>
            </div>
        </div>

        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                {{ form('servers/add', 'method' : 'post', 'autocomplete' : 'off', 'id' : 'postform') }}
                <div class="form-group">
                    <label for="title" class="mb-0">Server Title</label>
                    <p class="small text-muted">This will be displayed on the front page.</p>
                    {{ text_field('title', 'class' : 'form-control') }}
                </div>

                <div class="form-group">
                    <label for="title" class="mb-0">Category</label>
                    <p class="small text-muted">The game that your listing relates to.</p>
                    {{ select("game", games, 'using': ['id', 'title'], 'class' : 'form-control') }}
                </div>

                <div class="form-row">
                    <div class="col-6">
                        <div class="form-group">
                            <label for="title" class="mb-0">Server IP</label>
                            <p class="small text-muted">The Server IP. Will not be visible. Used for online status.</p>
                            {{ text_field('server_ip', 'class' : 'form-control') }}
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="website" class="mb-0">Server Port</label>
                            <p class="small text-muted">The Server Port. Will not be visible. Used for online status.</p>
                            {{ numeric_field('server_port', 'class' : 'form-control', 'min' : '0', 'max' : '65535') }}
                        </div>
                    </div>
                </div>

                {#<div class="form-group">
                    <label for="summary" class="mb-0">Description</label>
                    <p class="small text-muted">Displayed under your title. Keep it short and sweet. Must be between 20 and 200 chars.
                        Can contain only basic characters such as A-Z, 0-9, spaces, periods, and underscores..</p>
                    {{ text_field('summary', 'class' : 'form-control') }}
                </div>#}

                <div class="form-group">
                    <label for="website" class="mb-0">Website URL</label>
                    <p class="small text-muted">A link to your server's homepage. Leaving this blank will hide your listing.</p>
                    {{ text_field('website', 'class' : 'form-control') }}
                </div>

                <div class="form-group">
                    <label for="callback" class="mb-0">Callback URL</label>
                    <p class="small text-muted">Optional. For more on this, see our
                        {{ link_to('docs', 'documentation', 'target' : '_blank') }}</p>
                    {{ text_field('callback', 'class' : 'form-control') }}
                </div>

                <div class="form-group">
                    <label for="server_id" class="mb-0">Discord Server ID</label>
                    <p class="small text-muted">
                        Optional. Your discord server id. Click
                        <a target="_blank" href="https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-">here</a> for more info.
                        This will enable a discord block on your listing showing members and a join link automatically.
                        It's basically sorcery.
                        <span class="text-danger">Discord Widget must be enabled in your server's settings.</span>
                    </p>
                    {{ numeric_field('discord_id', 'class' : 'form-control') }}
                </div>

                <div class="form-group">
                    <label for="editor-form" class="mb-0">Information</label>
                    <p class="small text-muted">A more detailed overview of your server.</p>
                    <div id="editor" class="mb-3"></div>
                    <textarea name='info' id='editor-form' style='display:none'></textarea>
                </div>

                <div class="form-group">
                    {{ submit_button('Create Listing', 'class' : 'btn btn-primary') }}
                    {{ submit_button('Cancel', 'class' : 'btn btn-outline-danger float-right') }}
                </div>

                <div class="form-group mb-0">
                    <p class="mb-0">By creating a server, you agree to abide by our {{ link_to('terms', 'Terms of Service', 'target' : '_blank') }}.</p>
                </div>

                {{ hidden_field(security.getTokenKey(), 'value' : security.getToken()) }}
                {{ end_form() }}
            </div>
        </div>
    </div>
</div>

{{ partial('partials/quilljs') }}