{{ content() }}

{% if discord is defined %}

<div class="card border-0 shadow-sm bg-primary mb-3 overflow-hidden">
    <div class="card-body">
        <i class="fab fa-discord fa-3x mr-2 float-left text-white"></i>
        <h5 class="mb-0 text-white mt-1" style="line-height:1em !important;">
            {{ discord.getServerTitle() }}<br>
            <small class="text-white-50">{{ discord.getMembers()|count }} Members Online</small>
        </h5>
    </div>

    {% if discord.data.instant_invite %}
    {{ link_to(discord.data.instant_invite,
        'Join Server',
        'class' : 'btn btn-link text-white btn-block btn-sm py-3', false, 'target' : '_blank') }}
    {% endif %}
</div>
{% endif %}