<div class="row">
    <div class="col-sm-12 col-lg-8">
        {{ content() }}

        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body text-center">
                {{ image(server.banner_url, 'id' : 'server-banner', 'class' : 'img-fluid') }}
            </div>
            <div class="card-footer text-center">
                <button class="btn btn-primary" data-toggle="modal" data-target="#bannerModal">Upload Banner</button>
                <button class="btn btn-primary" data-toggle="modal" data-target="#imagesModal">Upload Images</button>
            </div>
        </div>

        {{ form('servers/edit/'~server.id, 'method' : 'post', 'autocomplete' : 'off') }}
        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                <div class="form-group">
                    <label for="title" class="mb-0">Server Title</label>
                    <p class="small text-muted">This will be displayed on the front page.</p>
                    {{ text_field('title', 'class' : 'form-control', 'value' : server.title) }}
                </div>
                <div class="form-group">
                    <label for="game" class="mb-0">Category</label>
                    <p class="small text-muted">The game that your listing relates to.</p>
                    {{ select("game", games, 'using': ['id', 'title'], 'class' : 'form-control', 'value' : server.game) }}
                </div>
                <div class="form-group">
                    <label for="website" class="mb-0">Website URL</label>
                    <p class="small text-muted">A link to your server's homepage. Leaving this blank will hide your listing.</p>
                    {{ text_field('website', 'class' : 'form-control', 'value' : server.website) }}
                </div>
                <div class="form-group mb-0">
                    {{ submit_button('Update', 'class' : 'btn btn-outline-primary') }}
                    {{ hidden_field(security.getTokenKey(), 'value' : security.getToken()) }}
                </div>
            </div>
        </div>
        {{ end_form() }}

        {{ form('servers/edit/'~server.id, 'method' : 'post', 'autocomplete' : 'off') }}
        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                <div class="form-group">
                    <label for="callback" class="mb-0">Callback URL</label>
                    <p class="small text-muted">Optional. Used for voting systems like MotiVote or FoxVote to send data
                        when a user makes a vote.</p>
                    {{ text_field('callback', 'class' : 'form-control', 'value' : server.callback) }}
                </div>
                <div class="form-group mb-0">
                    {{ submit_button('Update', 'class' : 'btn btn-outline-primary') }}
                    {{ hidden_field(security.getTokenKey(), 'value' : security.getToken()) }}
                </div>
            </div>
        </div>
        {{ end_form() }}

        {{ form('servers/edit/'~server.id, 'method' : 'post', 'autocomplete' : 'off') }}
        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                <div class="form-group">
                    <label for="discord_id" class="mb-0">Discord Server ID</label>
                    <p class="small text-muted" style="line-height:1em;">
                        Optional. Your discord server id. Click
                        <a target="_blank" href="https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-">here</a> for more info.
                        This will enable a discord block on your listing showing members and a join link automatically. It's basically sorcery.
                    </p>
                    {{ numeric_field('discord_id', 'class' : 'form-control', 'value' : server.discord_id) }}
                </div>
                <div class="form-group mb-0">
                    {{ submit_button('Update', 'class' : 'btn btn-outline-primary') }}
                    {{ hidden_field(security.getTokenKey(), 'value' : security.getToken()) }}
                </div>
            </div>
        </div>
        {{ end_form() }}

        {{ form('servers/edit/'~server.id, 'method' : 'post', 'autocomplete' : 'off') }}
        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                <div class="form-group">
                    <label for="meta_info" class="mb-0">Meta Description</label>
                    <p class="small text-muted">
                        A short description of your server. <a href="https://yoast.com/meta-descriptions/" target="_blank">https://yoast.com/meta-descriptions/</a>
                    </p>
                    {{ text_field('meta_info', 'class' : 'form-control', 'value' : server.meta_info, 'maxlength' : '155') }}
                </div>
                <div class="form-group">
                    <label for="meta_info" class="mb-0">Meta Tags</label>
                    <?php $tags = implode(",", json_decode($server->meta_tags, true)); ?>
                    <p class="small text-muted">Comma separated. Max 15. <a href="https://www.w3schools.com/tags/tag_meta.asp" target="_blank">https://www.w3schools.com/tags/tag_meta.asp</a></p>
                    {{ text_field('meta_tags', 'class' : 'form-control', 'value' : tags) }}
                </div>
                <div class="form-group mb-0">
                    {{ submit_button('Update', 'class' : 'btn btn-outline-primary') }}
                    {{ hidden_field(security.getTokenKey(), 'value' : security.getToken()) }}
                </div>
            </div>
        </div>
        {{ end_form() }}

        {{ form('servers/edit/'~server.id, 'method' : 'post', 'autocomplete' : 'off', 'id' : 'postform') }}
        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                <div class="form-group">
                    <label for="editor-form" class="mb-0">Information</label>
                    <p class="small text-muted">A more detailed overview of your server.</p>
                    <?php $desc = Functions::getPurifier()->purify($server->info); ?>
                    <div id="editor" class="mb-3">{{ desc }}</div>
                    <textarea name='info' id='editor-form' style='display:none'></textarea>
                </div>
                <div class="form-group mb-0">
                    {{ hidden_field(security.getTokenKey(), 'value' : security.getToken()) }}
                    {{ submit_button('Update', 'class' : 'btn btn-outline-primary') }}
                </div>
            </div>
        </div>
        {{ end_form() }}
    </div>

    <div class="col-sm-12 col-lg-4">
        <div class="card border-0 shadow-sm mb-0">
            <div class="card-header">Images</div>
            <div class="list-group list-group-flush justify-content-between" id="imagelist">
                {% set images = server.images %}
                {% if images %}
                {% for image in images %}
                {% if image is not null %}
                <div class="list-group-item d-flex justify-content-between align-items-center small">
                    {{ link_to(image, image, false, 'target' : '_blank') }}

                    <button id="delete" class="btn btn-link btn-sm"
                            data-image="{{ image }}"
                            data-server="{{ server.id }}">
                        <i class="fal fa-times text-danger"></i>
                    </button>
                </div>
                {% endif %}
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="bannerModal" tabindex="-1" role="dialog" aria-labelledby="bannerModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body text-center">

                <i class="fal fa-image text-discord fa-5x fa-fw my-4"></i>

                <h3 class="mb-2">Upload Banner</h3>
                <p class="small mb-4">PNG, GIF, or JPEG. Exactly 468x60, 3MB file size.</p>

                <div class="text-center">
                    <p id="bannerstatus">&nbsp;</p>

                    {{ form('servers/edit/', 'method' : 'post', 'enctype' : 'multipart/form-data', 'id' : 'uploadForm') }}
                    <input type="file" name="image" id="image" style="display: none;">
                    <input type="hidden" name="serverId" value="{{ server.id }}">
                    <button type="button" class="btn btn-primary" id="file-select">Select Image</button>
                    <button type="button" class="btn btn-link" data-dismiss="modal">Close</button>
                    {{ end_form() }}
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="imagesModal" tabindex="-1" role="dialog" aria-labelledby="imagesModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body text-center">

                <i class="fal fa-images text-discord fa-5x fa-fw my-4"></i>

                <h3 class="mb-2">Upload Images</h3>
                <p class="small mb-4">You may select up to 5 at a time. 10 max. Invalid images will be skipped.<br>
                    PNG, GIF, or JPEG. Max 1600x900, 3MB file size.</p>

                <div class="text-center">
                    <p id="upstatus">&nbsp;</p>

                    {{ form('servers/images', 'method' : 'post', 'enctype' : 'multipart/form-data','id' : 'imageForm') }}
                    <input type="file" name="images" id="images" style="display: none;" data-server="{{ server.id }}" multiple>
                    <button type="button" class="btn btn-primary" id="imagesUpload">Select Images</button>
                    <button type="button" class="btn btn-link" data-dismiss="modal">Close</button>
                    {{ end_form() }}
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>

{{ javascript_include("js/custom/images.delete.js?v="~time()) }}
{{ javascript_include("js/custom/banner.upload.js") }}
{{ javascript_include("js/custom/images.upload.js") }}

{{ partial('partials/quilljs') }}