<div class="row">
    <div class="col-sm-12 col-xl-8">
        {{ content() }}

        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                {% set banner = url(server.banner_url) %}
                <div class="banner" style="background:url({{ banner }}) top center #efefef;" id="banner">
                    {{ form('servers/edit/', 'method' : 'post', 'enctype' : 'multipart/form-data', 'id' : 'uploadForm') }}
                    <input type="file" name="image" id="image" style="display: none;">
                    <input type="hidden" name="uploadType" value="banner">
                    <input type="hidden" name="serverId" value="{{ server.id }}">
                    <button type="button" class="btn btn-link btn-sm text-white" id="file-select">
                        <i class="fas fa-camera fa-fw fa-2x"></i>
                    </button>
                    {{ hidden_field(security.getTokenKey(), 'value' : security.getToken()) }}
                    {{ end_form() }}
                </div>
                <div class="text-muted small mb-3">Image restrictions: PNG, JPG, or GIF, 468x60, 3MB file size</div>

                <div id="uploadStatus"></div>

                <div class="progress invisible" style="height: 20px;position: relative;">
                    <div class="progress-overlay w-100 text-dark"></div>
                    <div class="progress-bar" style="width: 0;"></div>
                </div>
            </div>
        </div>

        {{ form('servers/edit/'~server.id, 'method' : 'post', 'autocomplete' : 'off') }}
        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                <div class="form-group">
                    <label for="title" class="mb-0">Server Title</label>
                    <p class="small text-muted">This will be displayed on the front page.</p>
                    {{ text_field('title', 'class' : 'form-control', 'value' : server.title) }}
                </div>
                <div class="form-group">
                    <label for="game" class="mb-0">Category</label>
                    <p class="small text-muted">The game that your listing relates to.</p>
                    {{ select("game", games, 'using': ['id', 'title'], 'class' : 'form-control', 'value' : server.game) }}
                </div>
                <div class="form-group">
                    <label for="website" class="mb-0">Website URL</label>
                    <p class="small text-muted">A link to your server's homepage. Leaving this blank will hide your listing.</p>
                    {{ text_field('website', 'class' : 'form-control', 'value' : server.website) }}
                </div>
                <div class="form-group mb-0">
                    {{ submit_button('Update', 'class' : 'btn btn-outline-primary') }}
                    {{ hidden_field(security.getTokenKey(), 'value' : security.getToken()) }}
                </div>
            </div>
        </div>
        {{ end_form() }}

        {{ form('servers/edit/'~server.id, 'method' : 'post', 'autocomplete' : 'off') }}
        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                <div class="form-group">
                    <label for="callback" class="mb-0">Callback URL</label>
                    <p class="small text-muted">Optional. Used for voting systems like MotiVote or FoxVote to send data
                        when a user makes a vote.</p>
                    {{ text_field('callback', 'class' : 'form-control', 'value' : server.callback) }}
                </div>
                <div class="form-group mb-0">
                    {{ submit_button('Update', 'class' : 'btn btn-outline-primary') }}
                    {{ hidden_field(security.getTokenKey(), 'value' : security.getToken()) }}
                </div>
            </div>
        </div>
        {{ end_form() }}

        {{ form('servers/edit/'~server.id, 'method' : 'post', 'autocomplete' : 'off') }}
        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                <div class="form-group">
                    <label for="discord_id" class="mb-0">Discord Server ID</label>
                    <p class="small text-muted" style="line-height:1em;">
                        Optional. Your discord server id. Click
                        <a target="_blank" href="https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-">here</a> for more info.
                        This will enable a discord block on your listing showing members and a join link automatically. It's basically sorcery.
                    </p>
                    {{ numeric_field('discord_id', 'class' : 'form-control', 'value' : server.discord_id) }}
                </div>
                <div class="form-group mb-0">
                    {{ submit_button('Update', 'class' : 'btn btn-outline-primary') }}
                    {{ hidden_field(security.getTokenKey(), 'value' : security.getToken()) }}
                </div>
            </div>
        </div>
        {{ end_form() }}

        {{ form('servers/edit/'~server.id, 'method' : 'post', 'autocomplete' : 'off') }}
        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                <div class="form-group">
                    <label for="meta_info" class="mb-0">Meta Description</label>
                    <p class="small text-muted">
                        A short description of your server. <a href="https://yoast.com/meta-descriptions/" target="_blank">https://yoast.com/meta-descriptions/</a>
                    </p>
                    {{ text_field('meta_info', 'class' : 'form-control', 'value' : server.meta_info, 'maxlength' : '155') }}
                </div>
                <div class="form-group">
                    <label for="meta_info" class="mb-0">Meta Tags</label>
                    <?php $tags = implode(",", json_decode($server->meta_tags, true)); ?>
                    <p class="small text-muted">Comma separated. Max 15. <a href="https://www.w3schools.com/tags/tag_meta.asp" target="_blank">https://www.w3schools.com/tags/tag_meta.asp</a></p>
                    {{ text_field('meta_tags', 'class' : 'form-control', 'value' : tags) }}
                </div>
                <div class="form-group mb-0">
                    {{ submit_button('Update', 'class' : 'btn btn-outline-primary') }}
                    {{ hidden_field(security.getTokenKey(), 'value' : security.getToken()) }}
                </div>
            </div>
        </div>
        {{ end_form() }}

        {{ form('servers/edit/'~server.id, 'method' : 'post', 'autocomplete' : 'off', 'id' : 'postform') }}
        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                <div class="form-group">
                    <label for="editor-form" class="mb-0">Information</label>
                    <p class="small text-muted">A more detailed overview of your server.</p>
                    <?php $desc = Functions::getPurifier()->purify($server->info); ?>
                    <div id="editor" class="mb-3">{{ desc }}</div>
                    <textarea name='info' id='editor-form' style='display:none'></textarea>
                </div>
                <div class="form-group mb-0">
                    {{ hidden_field(security.getTokenKey(), 'value' : security.getToken()) }}
                    {{ submit_button('Update', 'class' : 'btn btn-outline-primary') }}
                </div>
            </div>
        </div>
        {{ end_form() }}

    </div>

    <div class="col-sm-12 col-xl-4">
        <div class="card border-0 shadow-sm mb-0">
            <div class="card-body">
                <h5>Rules:</h5>
                <p class="small text-muted">These must be followed to avoid your server being removed from our website. </p>
                <ul>
                    <li>Names must be clear. Remember, simplicity is key. clearer titles means more professional.</li>
                    <li>False advertising will not be tolerated.</li>
                    <li>Vulgar, hateful, or discriminatory remarks are not allowed.</li>
                    <li>
                        Images must be related to the listing, depicting clearly what the server has to offer. Images
                        containing any kind of pornography is strictly not allowed, and will result in a permanent ban.
                    </li>
                    <li>
                        Website links not related to the server listed will result in a permanent ban. (ie. listing is
                        linked to another unrelated website.)
                    </li>
                    <li>Affiliate links are not allowed.</li>
                    <li>
                        Server can not already be listed, by either title or by website url. Duplicates will be removed,
                        excessive duplicates will result in a ban.
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

{{ javascript_include("js/custom/banner.upload.js") }}
{{ partial('partials/quilljs') }}