{{ content() }}

<div class="row">
    <div class="col-sm-12 col-lg-4">
        <div class="card border-0 shadow-sm mb-3">
            <div class="list-group list-group-flush">
                <div class="list-group-item">Newest Servers</div>
                {% for newest in newest %}
                <a class="list-group-item  text-primary" style="line-height:1.0em;" href="{{ url('servers/view/'~getSeoTitle(newest)) }}">
                    {{ newest.title }}<br>
                    <small class="text-muted">Created {{ elapsed(newest.date_created) }}</small>
                </a>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="col-sm-12 col-lg-4">
        <div class="card border-0 shadow-sm mb-3">
            <div class="list-group list-group-flush">
                <div class="list-group-item">Most Liked Servers</div>
                {% for liked in mostLiked %}
                <a class="list-group-item text-primary" style="line-height:1.0em;" href="{{ url('servers/view/'~getSeoTitle(liked.server)) }}">
                    {{ liked.server.title }}<br>
                    <small class="text-muted">{{ liked.likes|number_format }} likes</small>
                </a>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="col-sm-12 col-lg-4">
        <div class="card border-0 shadow-sm mb-3">
            <div class="list-group list-group-flush">
                <div class="list-group-item">Most Votes (Accumulative)</div>
                {% for votedOn in mostVotes %}
                <a class="list-group-item text-primary" style="line-height:1.0em;" href="{{ url('servers/view/'~getSeoTitle(votedOn)) }}">
                    {{ votedOn.title }}<br>
                    <small class="text-muted">{{ votedOn.votes|number_format }} Votes</small>
                </a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>