{% set seo_title = getSeoTitle(server) %}

<div class="row">
    <div class="col-sm-12 col-lg-8">
        {{ content() }}
        <div id="alerts"></div>

        <div class="card border-0 shadow-sm mb-3 overflow-hidden">
            <div class="card-body p-2" style="height:210px;">
                <canvas id="voteChart" height="200px"></canvas>
            </div>
            <div class="card-footer text-center">
                {{ link_to(server.info.website, '<i class="fal fa-globe fa-fw"></i> Website', false, 'target' : '_blank',
                'class' : 'btn btn-primary',
                'data-toggle' : 'tooltip', 'title' : 'Visit Website') }}

                {{ link_to('', '<i class="fal fa-thumbs-up fa-fw"></i> Like', false, 'target' : '_blank',
                'class' : 'btn btn-primary',
                'id' : 'like', 'data-id' : server.id,
                'data-toggle' : 'tooltip', 'title' : 'Like this Server') }}

                {{ link_to('', '<i class="fal fa-flag fa-fw"></i> Report', false, 'target' : '_blank',
                'class' : 'btn btn-danger',
                'data-toggle' : 'modal', 'data-target' : '#reportModal') }}
            </div>
        </div>

        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body" id="serverInfo">
                {{ server.info.info }}
            </div>
        </div>

        <hr>

        {% if user is defined %}

        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                <div class="d-flex" id="comments">
                    <div class="flex-fill">
                        {% set avatar = avatar(user.user_id, user.avatar) %}
                        {{ image(avatar, 'width' : '48px;', 'class' : 'rounded-circle mr-3') }}
                    </div>
                    <div class="flex-fill w-100">
                        {{ form('servers/view/'~seo_title, 'method' : 'post', 'id' : 'comment-form', 'class' : 'form-inline') }}
                        <div class="form-group mb-0">
                            {{ text_field('comment', 'class' : 'form-control mr-2',
                            'placeholder' : 'Type a comment!',
                            'style' : 'width:300px') }}
                        </div>
                        {{ hidden_field('type', 'value' : 'comment') }}
                        {{ hidden_field(security.getTokenKey(), 'value' : security.getToken()) }}
                        <div class="form-group mb-0">
                            <button class="btn btn-primary" type="submit">
                                Submit
                            </button>
                        </div>
                        {{ end_form() }}
                    </div>
                </div>
            </div>
        </div>

        {% endif %}

        {% for comment in comments.items %}
        {% set avatar = avatar(comment.user_id, comment.avatar) %}

        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                <div class="d-flex">
                    <div class="flex-fill">
                        {{ image(avatar, 'width' : '50px;', 'class' : 'rounded-circle mr-3') }}
                    </div>
                    <div class="flex-fill w-100">
                        <span class="float-right text-muted">{{ date('d.m.Y', comment.date_posted) }}</span>

                        <p class="text-primary mb-0 text-uppercase">
                            {{ filter.sanitize(comment.username, 'string') }}
                        </p>

                        <p class="my-0">{{ filter.sanitize(comment.comment, 'string') }}</p>
                    </div>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>

    <div class="col-sm-12 col-lg-4">
        <div class="card border-0 shadow-sm mb-3 ">
            <div class="card-body">
                <p class="text-uppercase text-muted mb-0 small">STATUS</p>
                {% if server.is_online %}
                <h6 class="mb-0 text-success">
                    <span class="status status-online"></span>
                    ONLINE
                </h6>
                {% else %}
                <h6 class="mb-0 text-danger">
                    <span class="status status-offline"></span>
                    OFFLINE
                </h6>
                {% endif %}
            </div>
        </div>


        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                <p class="text-uppercase text-muted mb-0 small">Owner</p>
                <h6 class="mb-0">{{ server.owner_tag }}</h6>
                <p class="small mb-0 text-muted">ID: {{ server.owner_id }}</p>
            </div>
        </div>

        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                <p class="text-uppercase text-muted mb-0 small">Total Votes</p>
                <h6 class="mb-0">{{ server.votes|number_format }}</h6>
            </div>
        </div>

        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                <p class="text-uppercase text-muted mb-0 small">Likes</p>
                <h6 class="mb-0">{{ likes|number_format }}</h6>
            </div>
        </div>

        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                <p class="text-uppercase text-muted mb-0 small">Created</p>
                <h6 class="mb-0">{{ date('M. j, Y', server.date_created) }}</h6>
            </div>
        </div>

        <div id="discord"></div>
    </div>
</div>

<div class="modal fade" id="reportModal" tabindex="-1" role="dialog" aria-labelledby="reportModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Report {{ server.title }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {{ form('report', 'method' : 'post') }}
                <div class="form-group">
                    <label for="comment">Type a reason below as  to why you're reporting this server.</label>
                    {{ text_area('comment', 'class' : 'form-control mr-2', 'style' : 'min-width: 350px;max-height:300px;') }}
                </div>
                {{ hidden_field('type', 'value' : 'report') }}
                {{ hidden_field('serverId', 'value' : server.id) }}
                {{ hidden_field(security.getTokenKey(), 'value' : security.getToken()) }}
                <div class="form-group">
                    <button type="button" class="btn btn-secondary border-0" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary border-0">Submit Report</button>
                </div>
                {{ end_form() }}
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="imageModal" tabindex="-1" role="dialog" aria-labelledby="imageModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-body" id="img"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary border-0" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

{{ partial('servers/graph') }}

<script>
    var locked = false;

    var info   = $('#serverInfo');
    var links  = info.find('a');
    var images = info.find('img');

    $(document).on('click', '#screenshot', function(event) {
       let source = $(this).attr("src");
       $('#img').html('<img src="'+source+'" class="img-fluid">');
       $('#imageModal').modal();
    });

    setTimeout(function() {
        $.post('{{ url("servers/discord") }}', {
            server_id: '{{ server.info.discord_id }}'
        }, function(data) {
            $('#discord').html(data);
        });
    }, 1000);

    info.find('a').each(function() {
        $(this).attr('target', '_blank');
    });

    info.find('img').each(function() {
        $(this).addClass("img-fluid");
    });

    $(document).on('click', '#like', function(event) {
        event.preventDefault();

        if (locked) {
            return;
        }

        locked = true;

        var id = $(this).data("id");

        $.post('{{ url("servers/like") }}', {
            id: id
        }, function(data) {
            locked = false;
            try {
                var json = JSON.parse(data);
                var success = json.success;
                var msg = json.message;

                if (success) {
                    var count = json.count.amount;
                    $('#likes').html(count);
                }

                displayMsg(msg, success);
            } catch (err) {

            }
            console.log(data);
        });

    });

    $(function(){
        var hash = window.location.hash;
        hash && $('ul.nav a[href="' + hash + '"]').tab('show');

        $('.nav-tabs a').click(function (e) {
            $(this).tab('show');
            var scrollmem = $('body').scrollTop() || $('html').scrollTop();
            window.location.hash = this.hash;
            $('html,body').scrollTop(scrollmem);
        });
    });

    function displayMsg(message, success) {
        var type = success ? 'success' : 'danger';

        $('#alerts').html("<div class='alert alert-"+type+" alert-dismissible fade show'>" +
            "<button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">\n" +
            "<span aria-hidden=\"true\">&times;</span>\n" +
            "</button>"+message+"</div>");
    }
</script>