{% set seo_title = getSeoTitle(server) %}

<div class="row">
    <div class="col-sm-12 col-lg-8">
        {{ content() }}
        <div id="alerts"></div>

        <div class="card border-0 shadow-sm mb-3 bg-default">
            <div class="card-body p-2" style="height:210px;">
                <canvas id="voteChart" height="200px"></canvas>
            </div>
        </div>

        <div class="card border-0 shadow-sm mb-3">
            <div class="card-header bg-gradient-primary">
                <h4 class="mb-0 text-white">{{ server.title }}</h4>
            </div>

            <div class="card-body text-center" id="server-info">
                {{ link_to(server.info.website, '<i class="fal fa-globe fa-fw"></i> Website', false, 'target' : '_blank',
                    'class' : 'btn btn-primary',
                    'data-toggle' : 'tooltip', 'title' : 'Visit Website') }}

                {{ link_to('', '<i class="fal fa-thumbs-up fa-fw"></i> Like', false, 'target' : '_blank',
                    'class' : 'btn btn-primary',
                    'id' : 'like', 'data-id' : server.id,
                    'data-toggle' : 'tooltip', 'title' : 'Like this Server') }}

                {{ link_to('', '<i class="fal fa-flag fa-fw"></i> Report', false, 'target' : '_blank',
                    'class' : 'btn btn-danger',
                    'data-toggle' : 'modal', 'data-target' : '#reportModal') }}
            </div>
        </div>

        <div class="card border=0 shadow-sm mb-3 overflow-hidden">
            <ul class="nav nav-tabs pl-3 pt-3 bg-gradient-primary" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="info-tab" data-toggle="tab" href="#serverInfo" role="tab"
                       aria-controls="info" aria-selected="true">
                        Server Info
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="comments-tab" data-toggle="tab" href="#comments" role="tab"
                       aria-controls="comments" aria-selected="false">
                        Comments
                    </a>
                </li>
            </ul>

            <div class="tab-content">
                <div class="tab-pane show active p-3" id="serverInfo" role="tabpanel" aria-labelledby="info-tab">
                    {{ server.info.info }}
                </div>
                <div class="tab-pane" id="comments" role="tabpanel" aria-labelledby="comments-tab">
                    {% if user is defined %}
                    <div class="card-body">
                        <div class="comment-form"></div>
                        {{ form('servers/view/'~seo_title, 'method' : 'post', 'class' : 'form-inline', 'id' : 'comment-form') }}
                        <div class="form-group">
                            {{ text_field('comment', 'class' : 'form-control mr-2', 'placeholder' : 'Type a comment!',
                            'style' : 'min-width: 350px;') }}
                        </div>
                        {{ hidden_field('type', 'value' : 'comment') }}
                        {{ hidden_field(security.getTokenKey(), 'value' : security.getToken()) }}
                        <div class="form-group">
                            <button class="btn btn-dark" type="submit"><i class="fal fa-paper-plane"></i></button>
                        </div>
                        {{ end_form() }}
                    </div>
                    {% endif %}
                    <div class="list-group list-group-flush">
                        {% for comment in comments.items %}
                        {% set avatar = avatar(comment.user_id, comment.avatar) %}

                        <div class="list-group-item">
                            <div class="d-flex">
                                <div class="flex-fill">
                                    {{ image(avatar, 'width' : '42px;', 'class' : 'rounded-circle mr-3') }}
                                </div>
                                <div class="flex-fill w-100">
                                    <p class="small my-0">{{ filter.sanitize(comment.username, 'string') }} | {{ date('m/d/Y h:i A', comment.date_posted) }}</p>
                                    <p class="my-0">{{ filter.sanitize(comment.comment, 'string') }}</p>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>


        {% if comments.total_pages > 0 %}
        <nav aria-label="...">
            <ul class="pagination pagination-lg justify-content-center">
                <li class="page-item">
                    {{ link_to('servers/view/'~seo_title~'?page='~comments.first~'#comments',
                    '<i class="fal fa-angle-double-left"></i>',
                    'class' : 'page-link') }}
                </li>
                <li class="page-item mr-3">
                    {{ link_to('servers/view/'~seo_title~'?page='~comments.before~'#comments',
                    '<i class="fal fa-angle-left"></i>',
                    'class' : 'page-link') }}
                </li>

                <li class="page-item text-center text-muted" style="padding-top:12px;">
                    Page {{ comments.current }} of {{ comments.total_pages }}
                </li>

                <li class="page-item ml-3">
                    {{ link_to('servers/view/'~seo_title~'?page='~comments.next~'#comments',
                    '<i class="fal fa-angle-right"></i>',
                    'class' : 'page-link') }}
                </li>
                <li class="page-item">
                    {{ link_to('servers/view/'~seo_title~'?page='~comments.last~'#comments',
                    '<i class="fal fa-angle-double-right"></i>',
                    'class' : 'page-link') }}
                </li>
            </ul>
        </nav>

        {% endif %}

        {% set images = server.images|json_decode %}
        {% if images is not null and images is not empty %}
        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                {% for image in images %}
                <div class="img-holder d-inline-block mb-0" style="width:100px;height:75px;overflow: hidden;">
                    {{ image(image, 'class' : 'img-fluid', 'id' : 'screenshot') }}
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}


    </div>

    <div class="col-sm-12 col-lg-4">
        <div class="card border-0 shadow-sm mb-3">
            <div class="list-group list-group-flush">
                <div class="list-group-item">
                    Added By <span class="float-right text-right">{{ server.owner_tag }}<br><small>ID: {{ server.owner_id }}</small></span>
                </div>
                <div class="list-group-item">
                    Total Votes <span class="float-right">{{ server.votes }}</span>
                </div>
                <div class="list-group-item">
                    Likes <span class="float-right" id="likes">{{ likes }}</span>
                </div>
                <div class="list-group-item">
                    Date Created <span class="float-right">{{ date('M. j, Y', server.date_created) }}</span>
                </div>
            </div>
        </div>

        <div id="discord"></div>
    </div>
</div>

<div class="modal fade" id="reportModal" tabindex="-1" role="dialog" aria-labelledby="reportModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Report {{ server.title }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {{ form('report', 'method' : 'post') }}
                <div class="form-group">
                    <label for="comment">Type a reason below as  to why you're reporting this server.</label>
                    {{ text_area('comment', 'class' : 'form-control mr-2', 'style' : 'min-width: 350px;max-height:300px;') }}
                </div>
                {{ hidden_field('type', 'value' : 'report') }}
                {{ hidden_field('serverId', 'value' : server.id) }}
                {{ hidden_field(security.getTokenKey(), 'value' : security.getToken()) }}
                <div class="form-group">
                    <button type="button" class="btn btn-secondary border-0" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary border-0">Submit Report</button>
                </div>
                {{ end_form() }}
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="imageModal" tabindex="-1" role="dialog" aria-labelledby="imageModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-body" id="img"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary border-0" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

{{ partial('servers/graph') }}

<script>
    var locked = false;

    var info   = $('#serverInfo');
    var links  = info.find('a');
    var images = info.find('img');

    $(document).on('click', '#screenshot', function(event) {
       let source = $(this).attr("src");
       $('#img').html('<img src="'+source+'" class="img-fluid">');
       $('#imageModal').modal();
    });

    setTimeout(function() {
        $.post('{{ url("servers/discord") }}', {
            server_id: '{{ server.info.discord_id }}'
        }, function(data) {
            $('#discord').html(data);
        });
    }, 1000);

    info.find('a').each(function() {
        $(this).attr('target', '_blank');
    });

    info.find('img').each(function() {
        $(this).addClass("img-fluid");
    });

    $(document).on('click', '#like', function(event) {
        event.preventDefault();

        if (locked) {
            return;
        }

        locked = true;

        var id = $(this).data("id");

        $.post('{{ url("servers/like") }}', {
            id: id
        }, function(data) {
            locked = false;
            try {
                var json = JSON.parse(data);
                var success = json.success;
                var msg = json.message;

                if (success) {
                    var count = json.count.amount;
                    $('#likes').html(count);
                }

                displayMsg(msg, success);
            } catch (err) {

            }
            console.log(data);
        });

    });

    $(function(){
        var hash = window.location.hash;
        hash && $('ul.nav a[href="' + hash + '"]').tab('show');

        $('.nav-tabs a').click(function (e) {
            $(this).tab('show');
            var scrollmem = $('body').scrollTop() || $('html').scrollTop();
            window.location.hash = this.hash;
            $('html,body').scrollTop(scrollmem);
        });
    });

    function displayMsg(message, success) {
        var type = success ? 'success' : 'danger';

        $('#alerts').html("<div class='alert alert-"+type+" alert-dismissible fade show'>" +
            "<button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">\n" +
            "<span aria-hidden=\"true\">&times;</span>\n" +
            "</button>"+message+"</div>");
    }
</script>