<div class="row mb-5">
    <div class="col-sm-12 col-lg-10 offset-lg-1 text-center">
        <h2 class="text-primary">Server & Website Hosting</h2>
        <p>Still looking to host your own server or website? We have some recommendations that we trust.
            <br>Check them out below!
        </p>
    </div>
</div>

<div class="row pt-5 pb-4">
    <div class="col-12 col-md">
        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                <div class="text-center mb-5">
                    {{ image('img/misc/gsk.svg',
                        'height' : '100', 'class' : 'img-fluid', 'style' : 'height:100px;') }}
                </div>
                <p class="text-justify">
                    Game Server Kings offers reliable server hosting for all of your favorite games. Games include Rust,
                    7 days to Die, Unturned and more. Zero lag, always online, money back guarantee.
                </p>
                <p class="text-center mb-0">
                    {{ link_to('https://www.gameserverkings.com/', 'Visit', false,
                        'class' : 'btn btn-primary') }}
                </p>
            </div>
        </div>
    </div>

    <div class="col-12 col-md">
        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                <div class="text-center mb-5">
                    {{ image('img/misc/SiteTrec-Dark.svg', 'class' : 'img-fluid', 'style' : 'max-height:100px;') }}
                </div>
                <p class="text-justify">
                    SiteTrec is an ultrafast web and vps hosting company founded locally in the USA. We provide quality
                    hosting at an extremely affordable cost. No contracts, 14 day money back guarantee.
                </p>
                <p class="text-center mb-0">
                    {{ link_to('https://sitetrec.com/', 'Visit', false,
                        'class' : 'btn btn-primary') }}
                </p>
            </div>
        </div>
    </div>
</div>
