<div class="row mb-5">
    <div class="col-sm-12 col-lg-10 offset-lg-1 text-center">
        <h2>Premium Membership</h2>
        <p>Need a boost? Buying premium will give you instant votes, and votes at the beginning of the month.
            It's basically
        perpetual bonus votes! You'll also be able to use an animated banner, and get a highlighted background to boot!</p>
    </div>
</div>

<div class="row">
    <div class="col-sm-12 col-lg-3">
        <div class="card border-0 shadow-sm mb-3">
            <div class="card-header bg-dark border-0 text-white text-center">30 Days Premium</div>
            <div class="card-header bg-light border-0 text-info text-center bold-font">
                <h2 class="mb-0">$9.99</h2>
            </div>
            <div class="list-group list-group-flush text-center">
                <div class="list-group-item border-0">
                    +100 Instant Votes
                </div>
                <div class="list-group-item border-0">
                    <i class="fal fa-times text-danger"></i>
                </div>
                <div class="list-group-item border-0">
                    Animated Banner
                </div>
                <div class="list-group-item border-0">
                    Highlighted Background
                </div>
            </div>
            <div class="card-footer">
                <a href="" class="btn btn-info btn-block">Buy Now</a>
            </div>
        </div>
    </div>

    <div class="col-sm-12 col-lg-3">
        <div class="card border-0 shadow-sm">
            <div class="card-header bg-dark border-0 text-white text-center">60 Days Premium</div>
            <div class="card-header bg-light border-0 text-info text-center bold-font">
                <h2 class="mb-0">$18.99</h2>
            </div>
            <div class="list-group list-group-flush text-center">
                <div class="list-group-item border-0">
                    +200 Instant Votes
                </div>
                <div class="list-group-item border-0">
                    +200 Votes every reset
                </div>
                <div class="list-group-item border-0">
                    Animated Banner
                </div>
                <div class="list-group-item border-0">
                    Highlighted Background
                </div>
            </div>
            <div class="card-footer">
                <a href="" class="btn btn-info btn-block">Buy Now</a>
            </div>
        </div>
    </div>

    <div class="col-sm-12 col-lg-3">
        <div class="card border-0 shadow-sm mb-3">
            <div class="card-header bg-dark border-0 text-white text-center">90 Days Premium</div>
            <div class="card-header bg-light border-0 text-info text-center bold-font">
                <h2 class="mb-0">$27.99</h2>
            </div>
            <div class="list-group list-group-flush text-center">
                <div class="list-group-item border-0">
                    +300 Instant Votes
                </div>
                <div class="list-group-item border-0">
                    +300 Votes every reset
                </div>
                <div class="list-group-item border-0">
                    Animated Banner
                </div>
                <div class="list-group-item border-0">
                    Highlighted Background
                </div>
            </div>
            <div class="card-footer">
                <a href="" class="btn btn-info btn-block">Buy Now</a>
            </div>
        </div>
    </div>

    <div class="col-sm-12 col-lg-3">
        <div class="card border-0 shadow-sm mb-3">
            <div class="card-header bg-dark border-0 text-white text-center">180 Days Premium</div>
            <div class="card-header bg-light border-0 text-info text-center bold-font">
                <h2 class="mb-0">$54.99</h2>
            </div>
            <div class="list-group list-group-flush text-center">
                <div class="list-group-item border-0">
                    +500 Instant Votes
                </div>
                <div class="list-group-item border-0">
                    +500 Votes every reset
                </div>
                <div class="list-group-item border-0">
                    Animated Banner
                </div>
                <div class="list-group-item border-0">
                    Highlighted Background
                </div>
            </div>
            <div class="card-footer">
                <a href="" class="btn btn-info btn-block">Buy Now</a>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="card shadow-sm mb-3 border-0 text-secondary">
            <div class="card-body">
                <i>Not yet functional</i>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <h3>Premium Server Example</h3>
        <hr>
        <div class="card shadow-sm mb-3 border-0 text-secondary">
            <table class="table mb-0 tab" style="line-height: 1.2em">
                <tr class="bg-warning">
                    <td class="text-center px-4">
                        <h6 class="mb-0 text-warning"><i class="fas fa-star"></i></h6>
                    </td>
                    <td class="text-truncate" style="max-width:250px;">
                        <p class="text-secondary my-0 small text-uppercase">Server</p>
                        <h6 class="my-0 text-primary text-truncate">
                            <a rel="nofollow" href="#" class="text-info">Your Server Name</a>
                        </h6>
                    </td>
                    <td class="d-md-none d-lg-table-cell text-center">
                        {{ image('img/banner_light.png', 'class' : 'img-fluid server-banner') }}
                    </td>
                    <td class="text-right px-4" style="width:100px;">
                        <h6 class="mb-0">500</h6>
                        <small class="text-muted">Votes</small>
                    </td>
                </tr>
                <tr>
                    <td class="text-center px-4">
                        <h6 class="mb-0 text-muted">2</h6>
                    </td>
                    <td class="text-truncate" style="max-width:250px;">
                        <p class="text-secondary my-0 small text-uppercase">Server</p>
                        <h6 class="my-0 text-primary text-truncate">
                            <a rel="nofollow" href="#" class="text-info">Some other server</a>
                        </h6>
                    </td>
                    <td class="text-right px-4" style="width:100px;" colspan="2">
                        <h6 class="mb-0">0</h6>
                        <small class="text-muted">Votes</small>
                    </td>
                </tr>
                <tr>
                    <td class="text-center px-4">
                        <h6 class="mb-0 text-muted">3</h6>
                    </td>
                    <td class="text-truncate" style="max-width:250px;">
                        <p class="text-secondary my-0 small text-uppercase">Server</p>
                        <h6 class="my-0 text-primary text-truncate">
                            <a rel="nofollow" href="#" class="text-info">Some other server</a>
                        </h6>
                    </td>
                    <td class="text-right px-4" style="width:100px;" colspan="2">
                        <h6 class="mb-0">0</h6>
                        <small class="text-muted">Votes</small>
                    </td>
                </tr>
            </table>
        </div>

    </div>
</div>

{#
<div class="pricing-container">
    <div class="pricing card-group flex-column flex-lg-row mb-3">
        <div class="card card-pricing text-center px-3 mb-5 mb-lg-0">
            <span class="h6 w-60 mx-auto px-4 py-1 rounded-bottom bg-primary text-white">1 Month</span>
            <div class="card-header py-5 border-0">
                <div class="h1 text-primary text-center mb-0" data-pricing-value="12">$<span class="price">6</span><sup class="ml-1 h4 mt-1">99</sup></div>
            </div>
            <div class="card-body delimiter-top">
                <ul class="list-unstyled mb-4">
                    <li>Up to 5 users</li>
                    <li>Basic support on Github</li>
                    <li>Monthly updates</li>
                    <li>Free cancelation</li>
                </ul><button type="button" class="btn btn-sm btn-neutral mb-3">Order now</button>
            </div>
        </div>
        <div class="card card-pricing popular scale-110 text-center px-3 mb-5 mb-lg-0">
            <span class="h6 w-60 mx-auto px-4 py-1 rounded-bottom bg-primary text-white">3 Months</span>
            <div class="card-header py-5 border-0">
                <div class="h1 text-primary text-center mb-0" data-pricing-value="24">$<span class="price">19</span><sup class="ml-1 h4 mt-1">99</sup></div>
            </div>
            <div class="card-body delimiter-top">
                <ul class="list-unstyled mb-4">
                    <li>Up to 5 users</li>
                    <li>Basic support on Github</li>
                    <li>Monthly updates</li>
                    <li>Free cancelation</li>
                </ul><button type="button" class="btn btn-sm btn-neutral mb-3">Order now</button>
            </div>
        </div>
        <div class="card card-pricing text-center px-3 mb-5 mb-lg-0">
            <span class="h6 w-60 mx-auto px-4 py-1 rounded-bottom bg-primary text-white">6 Months</span>
            <div class="card-header py-5 border-0">
                <h1 class="text-primary text-center mb-0">
                    $39.99
                </h1>
            </div>
            <div class="card-body delimiter-top">
                <ul class="list-unstyled mb-4">
                    <li>Up to 5 users</li>
                    <li>Basic support on Github</li>
                    <li>Monthly updates</li>
                    <li>Free cancelation</li>
                </ul><button type="button" class="btn btn-sm btn-neutral mb-3">Order now</button>
            </div>
        </div>
    </div>
</div>
#}