<div class="row">
    <div class="col-sm-12 col-lg-3">
        {{ partial('dashboard/sidebar') }}
    </div>

    <div class="col-sm-12 col-lg-9">
        {{ content() }}

        <div class="card">
            <div class="card-header bg-gradient-primary text-white">
                Edit Theme
            </div>
            <div class="card-body">
                {{ form('dashboard/themes?edit='~name, 'method' : 'post', 'id' : 'addform') }}
                <div class="form-group">
                    <label for="name">Theme Name</label>
                    {{ text_field('name', 'class' : 'form-control', 'value' : name) }}
                </div>
                <div class="form-group position-relative" style="height:400px;">
                    <label for="editor-form" class="mb-0">Information</label>
                    <div id="ace-editor">{{ contents }}</div>
                    <textarea name='content' id='editor-form' style='display:none'></textarea>
                </div>
                <hr>
                <div class="form-group mb-0">
                    {{ submit_button('Save Changes', 'class' : 'btn btn-primary') }}
                    <span id="notice"></span>
                </div>
                {{ end_form() }}
            </div>
        </div>
    </div>
</div>

{{ javascript_include("js/ace/ace.js") }}

<script>
    let editor = ace.edit("ace-editor");
    editor.session.setMode("ace/mode/css");

    $('#addform').submit(function(event) {
        $(this).find("#editor-form").html(editor.getValue());
    });
</script>