<!DOCTYPE html>
<html lang="en-US">
<head>
	<meta charset="utf-8" />
    {% if get_title(false) is not '' %}
    <title>Rune-Nexus | {{ get_title(false) }}</title>
    {% else %}
    <title>Rune-Nexus</title>
    {% endif %}

    {% if meta_tags is defined %}
    <meta name="keywords" content="{{ meta_tags }}">
    {% else %}
    <meta name="keywords" content="toplist,topg,mmo,runescape,rsps,runescape,private,server,runelocus,rune-server,rune-list,runelist,top100,arena,top100">
    {% endif %}

    {% if description is defined %}
    <meta name="description" content="{{ filter.sanitize(description, 'string') }}">
    {% else %}
    <meta name="description" content="The most modern top-list built to-date. Completely free, feature rich, and easy to use!">
    {% endif %}

	<meta name="author" content="King Fox">
	<meta name="viewport" content="width=device-width, initial-scale=0.86">
	<link rel="shortcut icon" type="image/png" href="<?= base_url; ?>public/img/favicon.png"/>

    {{ stylesheet_link("css/fontawesome.min.css") }}

    {{ stylesheet_link("css/nucleo/css/nucleo.css") }}
    {{ stylesheet_link("css/argon.min.css") }}
    {{ stylesheet_link("css/stylesheet.css") }}

    {#{{ stylesheet_link("css/bootstrap.dark.css") }}#}

    {{ javascript_include("js/jquery-3.3.1.min.js") }}
    {{ javascript_include("js/bootstrap.bundle.min.js") }}
    {{ javascript_include("js/javascript.js?v="~time()) }}

    {{ javascript_include('js/aos.js?v='~time()) }}
    {{ stylesheet_link("css/aos.css?v="~time()) }}
</head>

<body>

    <header>
        <div class="overlay text-center text-white">
            <h1 class="mb-0">RuneNexus</h1>
            <p>A modern, free, and open source advertising platform.</p>
        </div>
    </header>

    <nav class="navbar navbar-expand-lg navbar-dark sticky-top" style="margin-top:-85px;">
        <div class="container">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#global-nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon custom-toggler"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-md-center" id="global-nav">
                <div class="navbar-collapse-header">
                    <div class="row">
                        <div class="col-6 collapse-brand">
                            Rune-Nexus
                        </div>
                        <div class="col-6 collapse-close">
                            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#global-nav" aria-controls="navbar-primary" aria-expanded="true" aria-label="Toggle navigation">
                                <span></span>
                                <span></span>
                            </button>
                        </div>
                    </div>
                </div>

                <ul class="navbar-nav" style="line-height:1.2em;">
                    <li class="nav-item text-lg-center">
                        {{ link_to('', 'Home', 'class' : 'nav-link') }}
                    </li>
                    <li class="nav-item text-lg-center">
                        {{ link_to('premium', 'Premium', 'class' : 'nav-link') }}
                    </li>
                    <li class="nav-item text-lg-center">
                        {{ link_to('advertising', 'Advertising', 'class' : 'nav-link') }}
                    </li>
                    <li class="nav-item text-lg-center">
                        {{ link_to('docs', 'Documentation', 'class' : 'nav-link') }}
                    </li>
                    <li class="nav-item text-lg-center">
                        {{ link_to('faq', 'FAQ', 'class' : 'nav-link') }}
                    </li>
                    <li class="nav-item text-lg-center">
                        {{ link_to('https://discord.gg/bmFN9A8', 'Join our Discord!', 'class' : 'nav-link text-discord', false, 'target' : '_blank') }}
                    </li>
                </ul>

                <ul class="navbar-nav ml-auto">
                    {% if user is defined %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            {{ link_to('profile', 'My Account', 'class' : 'dropdown-item') }}

                            {% if role is 'administrator' or role is 'owner' %}
                            {{ link_to('dashboard', 'Admin Dashboard', 'class' : 'dropdown-item') }}
                            {% endif %}

                            <div class="dropdown-divider"></div>
                            {{ link_to('logout', 'Logout', 'class' : 'dropdown-item text-danger') }}
                        </div>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#loginModal">
                            Login
                        </button>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <section class="content py-5">
        <div class="container">
            {{ content() }}
        </div>
    </section>

    <footer class="bg-dark py-5">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 text-center">
                    <h4>{{ image('img/logo_trans.png', 'height' : '100px', 'class' : 'my-3') }}</h4>

                    {{ link_to('', 'Home', 'class' : 'btn btn-link px-3 text-white') }}
                    {{ link_to('docs', 'Documentation', 'class' : 'btn btn-link px-3 text-white') }}
                    {{ link_to('terms', 'Terms of Service', 'class' : 'btn btn-link px-3 text-white') }}
                    {{ link_to('privacy', 'Privacy Policy', 'class' : 'btn btn-link px-3 text-white') }}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 text-center text-white-50">
                    Copyright &copy; {{ date("Y") }} Rune-Nexus | All Rights Reserved.
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-sm-12 text-center text-white-50">
                    {{ link_to('https://facebook.com/RuneNexusOfficial',
                        '<i class="fab fa-facebook-f fa-fw fa-2x"></i>', false,
                        'class' : 'btn btn-link text-white', 'target' : '_blank') }}

                    {{ link_to('https://github.com/OGKingFox/Toplist/',
                        '<i class="fab fa-github fa-fw fa-2x"></i>', false,
                        'class' : 'btn btn-link text-white', 'target' : '_blank') }}
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

{% if user is not defined %}
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body text-center">

                <i class="fab fa-discord text-discord fa-5x fa-fw my-4"></i>

                <h3 class="mb-0">Login with Discord</h3>
                <p class="small mb-4">Click below to log in using your Discord Account.</p>

                <div class="text-center">
                    <button type="button" class="btn btn-primary" id="loginbtn">Continue</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).on("click", "#loginbtn", function(event) {
        $(this).addClass("disabled");
        $(this).attr("disabled", "disabled");
        $(this).html("<i class='fal fa-spinner fa-pulse fa-fw'></i>");

        $.get('{{ url("login/url") }}', function(data) {
            let url = data.toString();

            setTimeout(function() {
                window.location = url;
            }, 750);
        });
    });
</script>
{% endif %}