<!DOCTYPE html>
<html lang="en-US">
<head>
	<meta charset="utf-8" />
	<title>Runecore</title>
	<meta name="keywords" content="">
	<meta name="description" content="">
	<meta name="author" content="King Fox">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" type="image/png" href="<?= base_url; ?>public/img/favicon.png"/>

    {{ stylesheet_link("css/bootstrap.min.css") }}
    {{ stylesheet_link("css/bootstrap-custom.css") }}
    {{ stylesheet_link("css/fontawesome-all.css") }}
    {{ stylesheet_link("css/stylesheet.css") }}
    {{ stylesheet_link("css/aos.css") }}

    {{ javascript_include("js/jquery-3.3.1.min.js") }}
    {{ javascript_include("js/popper.min.js") }}
    {{ javascript_include("js/bootstrap.min.js") }}
    {{ javascript_include("js/aos.js") }}
    {{ javascript_include("js/javascript.js") }}
</head>
<body class="py-0 my-0">

    {{ content() }}
    
</body>
</html>