<div class="row">
    <div class="col-sm-12 col-lg-3">
        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body text-center">
                {% set avatar = avatar(user.user_id, user.avatar) %}

                <div class="mb-3">{{ image(avatar, 'class' : 'rounded-circle', 'width' : '125') }}</div>

                <div class="text-truncate m-auto h5 text-primary" style="max-width: 200px;">
                    {{ filter.sanitize(user.username, 'string') }}
                </div>
                <p class="small text-muted">ID: {{ user.user_id }}</p>

                {{ user.role|capitalize }}
            </div>
        </div>

        <div class="card border-0 shadow-sm mb-3">
            <div class="list-group list-group-flush">
                <div class="list-group-item" style="line-height:1.2em;">
                    <small class="text-muted">Premium Status</small><br>
                    {% if user.premium_expires > time() %}
                    <span class="text-success">Active</span>
                    {% else %}
                    <span class="text-danger">Inactive</span>
                    {% endif %}
                </div>

                {% if user.premium_expires > time() %}
                <div class="list-group-item" style="line-height:1.2em;">
                    <small class="text-muted">Expires</small><br>
                    {{ date('M. d, Y g:i A', user.premium_expires) }}
                </div>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="col-sm-12 col-lg-9">
        {{ content() }}

        <div class="card border-0 shadow-sm mb-3">
            <div class="card-header bg-gradient-primary" style="line-height:1em;">
                {{ link_to('servers/add',
                    '<i class="fal fa-plus-circle fa-fw"></i> Add Server',
                    'class' : 'btn btn-primary float-right') }}

                <h5 class="mb-0 text-white">My Servers</h5>
                <p class="mb-0 small text-white-50">Manage all of your servers in one place.</p>
            </div>
            <table class="table table-hover mb-0" style="line-height:1em;">
                {% for server in servers %}
                <tr>
                    <td>{{ link_to('view/'~getSeoTitle(server), server.title, 'target' : '_blank') }}</td>
                    <td>
                        <p class="mb-0">{{ server.votes|number_format }}</p>
                        <small class="text-muted">Votes</small>
                    </td>
                    <td>
                        <p class="mb-0">{{ server.likes|number_format }}</p>
                        <small class="text-muted">Likes</small>
                    </td>
                    <td>
                        {{ date("M. d, Y", server.date_created) }}
                    </td>
                    <td class="text-right">
                        {{ link_to('servers/edit/'~server.id, 'Edit', 'class' : 'btn btn-outline-primary btn-sm') }}
                        {{ link_to('', 'Delete', 'class' : 'btn btn-outline-danger btn-sm', 'id' : 'delete', 'data-id' : server.id) }}
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
<script>
    let timerInterval;

    $(document).on("click", "#delete", function(event) {
        event.preventDefault();

        var id = $(this).data("id");

        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.value) {
                $.post("{{ url('servers/delete') }}", {
                    id: id,
                }, function(data) {
                    console.log(data);

                    try {
                        let json = JSON.parse(data);

                        Swal.fire({
                            title: json.success ? 'Deleted!' : 'Error',
                            html: json.message,
                            type: json.error ? 'error' : 'success',
                            timer: 2000,
                            showConfirmButton: false,
                            onBeforeOpen: () => {
                                timerInterval = setInterval(() => {}, 100)
                            },
                            onClose: () => {
                                clearInterval(timerInterval);
                                window.location.reload();
                            }
                        });
                    } catch (err) {
                        console.log(err);
                    }
                    locked = false;
                });
            } else {
                locked = false;
            }
        });
    });
</script>