<div class="row">
    {{ partial('profile/sidebar') }}

    <div class="col-sm-12 col-lg-9">
        {{ content() }}

        <div class="card border-0 shadow-sm mb-3">
            <div class="card-body">
                {{ form('profile/settings', 'method' : 'post', 'class' : 'form-inline') }}
                <div class="form-group mr-2">
                    <select name="theme_id" class="custom-select" id="theme_id">
                        <option value="-1" {{ user.theme_id is -1 ? 'selected' : '' }}>Default Theme</option>

                        {% for theme in themes %}
                        {% set selected = user.theme_id is theme['file'] ? 'selected' : '' %}
                        <option value="{{ theme['file'] }}" {{ selected }}>{{ theme['file'] }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    {{ submit_button('Apply', 'class' : 'btn btn-primary') }}
                </div>
                {{ end_form() }}
            </div>
        </div>
    </div>
</div>